# Real data analysis project in `duckdb`

This is again just the prologue to allow the notebooks running standalone in a local Jupyter installation and in Google Colab.

In [1]:
import os
try:
    import google.colab
    IN_COLAB = True
    if not os.path.isdir("/content/oreilly-duckdb"):
        os.system("git clone https://github.com/datanizing/oreilly-duckdb")
    data = "/content/oreilly-duckdb/data"
except:
    IN_COLAB = False
    data = "data"

## Download data

In [2]:
from tqdm.auto import tqdm
import requests

response = requests.get("https://www.kaggle.com/api/v1/datasets/download/Cornell-University/arxiv", stream=True)
total_size = int(response.headers.get("content-length", 0))
block_size = 1024

with tqdm(total=total_size, unit="B", unit_scale=True) as progress_bar:
    with open("arxiv.zip", "wb") as file:
        for data in response.iter_content(block_size):
            progress_bar.update(len(data))
            file.write(data)

if total_size != 0 and progress_bar.n != total_size:
    print("Could not download file")

  0%|          | 0.00/1.80G [00:00<?, ?B/s]

In [4]:
import duckdb
duckdb.sql("INSTALL zipfs FROM community; LOAD zipfs")

If the extension does not work for you, you can 
extract he files manually or use the following code
to extract the files (adjust the names in the `duckdb`
statements appropriately):
```python
from zipfile import ZipFile
with ZipFile("arxiv.zip", 'r') as zip_ref:
    zip_ref.extractall(".")
```

First convert to `parquet` format so we have fast access. We will use
the current timestamp in the converted `parquet` file. There are a 
few reasons for that:
* We don't want to overwrite an already existing converted `parquet` file.
* If we use more sophisticated analysis (like NLP or LLMs) on the data, we
  would like to restrict that on the new data (incremental updates).

In [5]:
from datetime import datetime
today = datetime.now().strftime('%Y%m%d')

In [7]:
%%time
duckdb.sql(f"COPY (SELECT * FROM 'zip://arxiv.zip/arxiv-metadata-oai-snapshot.json') TO 'arxiv-{today}.parquet'")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

CPU times: user 1min 37s, sys: 13.2 s, total: 1min 50s
Wall time: 41.4 s

In [9]:
duckdb.sql(f"FROM 'arxiv-{today}.parquet' LIMIT 5").pl()

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ submitter ┆ authors   ┆ title     ┆ … ┆ abstract  ┆ versions  ┆ update_da ┆ authors_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ te        ┆ parsed   │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ list[stru ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ ct[2]]    ┆ date      ┆ list[lis │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ t[str]]  │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0704.0001 ┆ Pavel     ┆ C.        ┆ Calculati ┆ … ┆ A fully   ┆ [{"v1","M ┆ 2008-11-2 ┆ [["Baláz │
│           ┆ Nadolsky  ┆ Bal\'azs, ┆ on of     ┆   ┆ different ┆ on, 2 Apr ┆ 6         ┆ s",      │
│           ┆           ┆ E. L.     ┆ prompt    ┆   ┆ ial       ┆ 2007      ┆           ┆ "C.",    │
│           ┆           ┆ Berger,   ┆ diphoton… ┆   ┆ calcula…  ┆ 19:18:…   ┆           ┆ ""],     │
│           ┆           ┆ P. …      ┆           ┆   ┆           ┆           ┆           ┆ ["Berge… │
│ 0704.0002 ┆ Louis     ┆ Ileana    ┆ Sparsity- ┆ … ┆ We        ┆ [{"v1","S ┆ 2008-12-1 ┆ [["Strei │
│           ┆ Theran    ┆ Streinu   ┆ certifyin ┆   ┆ describe  ┆ at, 31    ┆ 3         ┆ nu", "Il │
│           ┆           ┆ and Louis ┆ g Graph   ┆   ┆ a new alg ┆ Mar 2007  ┆           ┆ eana",   │
│           ┆           ┆ Thera…    ┆ Deco…     ┆   ┆ orithm,…  ┆ 02:26…    ┆           ┆ ""], ["… │
│ 0704.0003 ┆ Hongjun   ┆ Hongjun   ┆ The       ┆ … ┆ The       ┆ [{"v1","S ┆ 2008-01-1 ┆ [["Pan", │
│           ┆ Pan       ┆ Pan       ┆ evolution ┆   ┆ evolution ┆ un, 1 Apr ┆ 3         ┆ "Hongjun │
│           ┆           ┆           ┆ of the    ┆   ┆ of Earth- ┆ 2007      ┆           ┆ ", ""]]  │
│           ┆           ┆           ┆ Earth-Moo ┆   ┆ Moon …    ┆ 20:46:…   ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 0704.0004 ┆ David     ┆ David     ┆ A determi ┆ … ┆ We show   ┆ [{"v1","S ┆ 2007-05-2 ┆ [["Calla │
│           ┆ Callan    ┆ Callan    ┆ nant of   ┆   ┆ that a    ┆ at, 31    ┆ 3         ┆ n",      │
│           ┆           ┆           ┆ Stirling  ┆   ┆ determina ┆ Mar 2007  ┆           ┆ "David", │
│           ┆           ┆           ┆ cycl…     ┆   ┆ nt o…     ┆ 03:16…    ┆           ┆ ""]]     │
│ 0704.0005 ┆ Alberto   ┆ Wael Abu- ┆ From      ┆ … ┆ In this   ┆ [{"v1","M ┆ 2013-10-1 ┆ [["Abu-S │
│           ┆ Torchinsk ┆ Shammala  ┆ dyadic    ┆   ┆ paper we  ┆ on, 2 Apr ┆ 5         ┆ hammala" │
│           ┆ y         ┆ and       ┆ $\Lambda_ ┆   ┆ show how  ┆ 2007      ┆           ┆ ,        │
│           ┆           ┆ Alberto … ┆ {\alpha}$ ┆   ┆ to…       ┆ 18:09:…   ┆           ┆ "Wael",  │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆ ""],…    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [40]:
duckdb.sql(f"SELECT count(*) FROM 'arxiv-{today}.parquet' LIMIT 5").pl()

shape: (1, 1)
┌──────────────┐
│ count_star() │
│ ---          │
│ i64          │
╞══════════════╡
│ 3120363      │
└──────────────┘

In [19]:
duckdb.sql(f"DESCRIBE FROM 'arxiv-{today}.parquet'").pl().show(limit=15, fmt_str_lengths=100)

column_name,column_type,null,key,default,extra
str,str,str,str,str,str
"""id""","""VARCHAR""","""YES""",null,null,null
"""submitter""","""VARCHAR""","""YES""",null,null,null
"""authors""","""VARCHAR""","""YES""",null,null,null
"""title""","""VARCHAR""","""YES""",null,null,null
"""comments""","""VARCHAR""","""YES""",null,null,null
"""journal-ref""","""VARCHAR""","""YES""",null,null,null
"""doi""","""VARCHAR""","""YES""",null,null,null
"""report-no""","""VARCHAR""","""YES""",null,null,null
"""categories""","""VARCHAR""","""YES""",null,null,null
"""license""","""VARCHAR""","""YES""",null,null,null
"""abstract""","""VARCHAR""","""YES""",null,null,null
"""versions""","""STRUCT(""version"" VARCHAR, created VARCHAR)[]""","""YES""",null,null,null
"""update_date""","""DATE""","""YES""",null,null,null
"""authors_parsed""","""VARCHAR[][]""","""YES""",null,null,null

In [29]:
duckdb.sql(f"SELECT id, unnest(versions) FROM 'arxiv-{today}.parquet' LIMIT 5").pl()

shape: (5, 2)
┌───────────┬─────────────────────────────────┐
│ id        ┆ unnest(versions)                │
│ ---       ┆ ---                             │
│ str       ┆ struct[2]                       │
╞═══════════╪═════════════════════════════════╡
│ 0704.0001 ┆ {"v1","Mon, 2 Apr 2007 19:18:4… │
│ 0704.0001 ┆ {"v2","Tue, 24 Jul 2007 20:10:… │
│ 0704.0002 ┆ {"v1","Sat, 31 Mar 2007 02:26:… │
│ 0704.0002 ┆ {"v2","Sat, 13 Dec 2008 17:26:… │
│ 0704.0003 ┆ {"v1","Sun, 1 Apr 2007 20:46:5… │
└───────────┴─────────────────────────────────┘

In [28]:
duckdb.sql(f"SELECT id, unnest(versions, recursive := true) FROM 'arxiv-{today}.parquet' LIMIT 5").pl()

shape: (5, 3)
┌───────────┬─────────┬───────────────────────────────┐
│ id        ┆ version ┆ created                       │
│ ---       ┆ ---     ┆ ---                           │
│ str       ┆ str     ┆ str                           │
╞═══════════╪═════════╪═══════════════════════════════╡
│ 0704.0001 ┆ v1      ┆ Mon, 2 Apr 2007 19:18:42 GMT  │
│ 0704.0001 ┆ v2      ┆ Tue, 24 Jul 2007 20:10:27 GMT │
│ 0704.0002 ┆ v1      ┆ Sat, 31 Mar 2007 02:26:18 GMT │
│ 0704.0002 ┆ v2      ┆ Sat, 13 Dec 2008 17:26:00 GMT │
│ 0704.0003 ┆ v1      ┆ Sun, 1 Apr 2007 20:46:54 GMT  │
└───────────┴─────────┴───────────────────────────────┘

In [35]:
duckdb.sql(f"SELECT id, unnest(versions, recursive := true) FROM 'arxiv-{today}.parquet' WHERE version='v1' LIMIT 5").pl()

BinderException: Binder Error: Referenced column "version" not found in FROM clause!
Candidate bindings: "versions", "report-no", "categories", "comments", "license"

In [41]:
duckdb.sql(f"WITH publications AS (SELECT *, unnest(versions, recursive := true), FROM 'arxiv-{today}.parquet')\
             SELECT * EXCLUDE(versions) FROM publications WHERE version='v1' LIMIT 5").pl()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

shape: (5, 15)
┌───────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬─────────┬───────────┐
│ id        ┆ submitter  ┆ authors   ┆ title     ┆ … ┆ update_da ┆ authors_p ┆ version ┆ created   │
│ ---       ┆ ---        ┆ ---       ┆ ---       ┆   ┆ te        ┆ arsed     ┆ ---     ┆ ---       │
│ str       ┆ str        ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ str     ┆ str       │
│           ┆            ┆           ┆           ┆   ┆ date      ┆ list[list ┆         ┆           │
│           ┆            ┆           ┆           ┆   ┆           ┆ [str]]    ┆         ┆           │
╞═══════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═════════╪═══════════╡
│ 0704.0001 ┆ Pavel      ┆ C.        ┆ Calculati ┆ … ┆ 2008-11-2 ┆ [["Balázs ┆ v1      ┆ Mon, 2    │
│           ┆ Nadolsky   ┆ Bal\'azs, ┆ on of     ┆   ┆ 6         ┆ ", "C.",  ┆         ┆ Apr 2007  │
│           ┆            ┆ E. L.     ┆ prompt    ┆   ┆           ┆ ""],      ┆         ┆ 19:18:42  │
│           ┆            ┆ Berger,   ┆ diphoton… ┆   ┆           ┆ ["Berge…  ┆         ┆ GMT       │
│           ┆            ┆ P. …      ┆           ┆   ┆           ┆           ┆         ┆           │
│ 0704.0002 ┆ Louis      ┆ Ileana    ┆ Sparsity- ┆ … ┆ 2008-12-1 ┆ [["Strein ┆ v1      ┆ Sat, 31   │
│           ┆ Theran     ┆ Streinu   ┆ certifyin ┆   ┆ 3         ┆ u",       ┆         ┆ Mar 2007  │
│           ┆            ┆ and Louis ┆ g Graph   ┆   ┆           ┆ "Ileana", ┆         ┆ 02:26:18  │
│           ┆            ┆ Thera…    ┆ Deco…     ┆   ┆           ┆ ""], ["…  ┆         ┆ GMT       │
│ 0704.0003 ┆ Hongjun    ┆ Hongjun   ┆ The       ┆ … ┆ 2008-01-1 ┆ [["Pan",  ┆ v1      ┆ Sun, 1    │
│           ┆ Pan        ┆ Pan       ┆ evolution ┆   ┆ 3         ┆ "Hongjun" ┆         ┆ Apr 2007  │
│           ┆            ┆           ┆ of the    ┆   ┆           ┆ , ""]]    ┆         ┆ 20:46:54  │
│           ┆            ┆           ┆ Earth-Moo ┆   ┆           ┆           ┆         ┆ GMT       │
│           ┆            ┆           ┆ …         ┆   ┆           ┆           ┆         ┆           │
│ 0704.0004 ┆ David      ┆ David     ┆ A determi ┆ … ┆ 2007-05-2 ┆ [["Callan ┆ v1      ┆ Sat, 31   │
│           ┆ Callan     ┆ Callan    ┆ nant of   ┆   ┆ 3         ┆ ",        ┆         ┆ Mar 2007  │
│           ┆            ┆           ┆ Stirling  ┆   ┆           ┆ "David",  ┆         ┆ 03:16:14  │
│           ┆            ┆           ┆ cycl…     ┆   ┆           ┆ ""]]      ┆         ┆ GMT       │
│ 0704.0005 ┆ Alberto    ┆ Wael Abu- ┆ From      ┆ … ┆ 2013-10-1 ┆ [["Abu-Sh ┆ v1      ┆ Mon, 2    │
│           ┆ Torchinsky ┆ Shammala  ┆ dyadic    ┆   ┆ 5         ┆ ammala",  ┆         ┆ Apr 2007  │
│           ┆            ┆ and       ┆ $\Lambda_ ┆   ┆           ┆ "Wael",   ┆         ┆ 18:09:58  │
│           ┆            ┆ Alberto … ┆ {\alpha}$ ┆   ┆           ┆ ""],…     ┆         ┆ GMT       │
│           ┆            ┆           ┆ …         ┆   ┆           ┆           ┆         ┆           │
└───────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴─────────┴───────────┘

Why so slow? All columns must be read. For now only `id` and `created`:

In [43]:
duckdb.sql(f"WITH publications AS (SELECT *, unnest(versions, recursive := true), FROM 'arxiv-{today}.parquet')\
             SELECT id, created FROM publications WHERE version='v1' LIMIT 5").pl()

shape: (5, 2)
┌───────────┬───────────────────────────────┐
│ id        ┆ created                       │
│ ---       ┆ ---                           │
│ str       ┆ str                           │
╞═══════════╪═══════════════════════════════╡
│ 0704.0001 ┆ Mon, 2 Apr 2007 19:18:42 GMT  │
│ 0704.0002 ┆ Sat, 31 Mar 2007 02:26:18 GMT │
│ 0704.0003 ┆ Sun, 1 Apr 2007 20:46:54 GMT  │
│ 0704.0004 ┆ Sat, 31 Mar 2007 03:16:14 GMT │
│ 0704.0005 ┆ Mon, 2 Apr 2007 18:09:58 GMT  │
└───────────┴───────────────────────────────┘

Now parse the date

In [47]:
duckdb.sql(f"WITH publications AS (SELECT *, unnest(versions, recursive := true), FROM 'arxiv-{today}.parquet')\
             SELECT id, created, strptime(created, '%a, %d %b %Y %H:%M:%S %Z') FROM publications WHERE version='v1' LIMIT 5").pl()

shape: (5, 3)
┌───────────┬───────────────────────────────┬─────────────────────────────────┐
│ id        ┆ created                       ┆ strptime(created, '%a, %d %b %… │
│ ---       ┆ ---                           ┆ ---                             │
│ str       ┆ str                           ┆ datetime[μs, Etc/UTC]           │
╞═══════════╪═══════════════════════════════╪═════════════════════════════════╡
│ 0704.0001 ┆ Mon, 2 Apr 2007 19:18:42 GMT  ┆ 2007-04-02 19:18:42 UTC         │
│ 0704.0002 ┆ Sat, 31 Mar 2007 02:26:18 GMT ┆ 2007-03-31 02:26:18 UTC         │
│ 0704.0003 ┆ Sun, 1 Apr 2007 20:46:54 GMT  ┆ 2007-04-01 20:46:54 UTC         │
│ 0704.0004 ┆ Sat, 31 Mar 2007 03:16:14 GMT ┆ 2007-03-31 03:16:14 UTC         │
│ 0704.0005 ┆ Mon, 2 Apr 2007 18:09:58 GMT  ┆ 2007-04-02 18:09:58 UTC         │
└───────────┴───────────────────────────────┴─────────────────────────────────┘

Make categories a list

In [49]:
duckdb.sql(f"WITH publications AS (SELECT *, unnest(versions, recursive := true), FROM 'arxiv-{today}.parquet')\
             SELECT id, string_split(categories, ' ') FROM publications WHERE version='v1' LIMIT 5").pl()

shape: (5, 2)
┌───────────┬───────────────────────────────┐
│ id        ┆ string_split(categories, ' ') │
│ ---       ┆ ---                           │
│ str       ┆ list[str]                     │
╞═══════════╪═══════════════════════════════╡
│ 0704.0001 ┆ ["hep-ph"]                    │
│ 0704.0002 ┆ ["math.CO", "cs.CG"]          │
│ 0704.0003 ┆ ["physics.gen-ph"]            │
│ 0704.0004 ┆ ["math.CO"]                   │
│ 0704.0005 ┆ ["math.CA", "math.FA"]        │
└───────────┴───────────────────────────────┘

Save intermediate results as `parquet`

In [53]:
duckdb.sql(f"DESCRIBE FROM 'arxiv-{today}.parquet'").pl().show(limit=15, fmt_str_lengths=100)

column_name,column_type,null,key,default,extra
str,str,str,str,str,str
"""id""","""VARCHAR""","""YES""",null,null,null
"""submitter""","""VARCHAR""","""YES""",null,null,null
"""authors""","""VARCHAR""","""YES""",null,null,null
"""title""","""VARCHAR""","""YES""",null,null,null
"""comments""","""VARCHAR""","""YES""",null,null,null
"""journal-ref""","""VARCHAR""","""YES""",null,null,null
"""doi""","""VARCHAR""","""YES""",null,null,null
"""report-no""","""VARCHAR""","""YES""",null,null,null
"""categories""","""VARCHAR""","""YES""",null,null,null
"""license""","""VARCHAR""","""YES""",null,null,null
"""abstract""","""VARCHAR""","""YES""",null,null,null
"""versions""","""STRUCT(""version"" VARCHAR, created VARCHAR)[]""","""YES""",null,null,null
"""update_date""","""DATE""","""YES""",null,null,null
"""authors_parsed""","""VARCHAR[][]""","""YES""",null,null,null

In [54]:
duckdb.sql(f"WITH publications AS (SELECT *, unnest(versions, recursive := true), FROM 'arxiv-{today}.parquet')\
             SELECT *, string_split(categories, ' ') AS categories, FROM publications WHERE version='v1' LIMIT 5").pl()

shape: (5, 17)
┌───────────┬────────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ id        ┆ submitter  ┆ authors   ┆ title     ┆ … ┆ authors_p ┆ version ┆ created   ┆ categorie │
│ ---       ┆ ---        ┆ ---       ┆ ---       ┆   ┆ arsed     ┆ ---     ┆ ---       ┆ s_1       │
│ str       ┆ str        ┆ str       ┆ str       ┆   ┆ ---       ┆ str     ┆ str       ┆ ---       │
│           ┆            ┆           ┆           ┆   ┆ list[list ┆         ┆           ┆ list[str] │
│           ┆            ┆           ┆           ┆   ┆ [str]]    ┆         ┆           ┆           │
╞═══════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ 0704.0001 ┆ Pavel      ┆ C.        ┆ Calculati ┆ … ┆ [["Balázs ┆ v1      ┆ Mon, 2    ┆ ["hep-ph" │
│           ┆ Nadolsky   ┆ Bal\'azs, ┆ on of     ┆   ┆ ", "C.",  ┆         ┆ Apr 2007  ┆ ]         │
│           ┆            ┆ E. L.     ┆ prompt    ┆   ┆ ""],      ┆         ┆ 19:18:42  ┆           │
│           ┆            ┆ Berger,   ┆ diphoton… ┆   ┆ ["Berge…  ┆         ┆ GMT       ┆           │
│           ┆            ┆ P. …      ┆           ┆   ┆           ┆         ┆           ┆           │
│ 0704.0002 ┆ Louis      ┆ Ileana    ┆ Sparsity- ┆ … ┆ [["Strein ┆ v1      ┆ Sat, 31   ┆ ["math.CO │
│           ┆ Theran     ┆ Streinu   ┆ certifyin ┆   ┆ u",       ┆         ┆ Mar 2007  ┆ ",        │
│           ┆            ┆ and Louis ┆ g Graph   ┆   ┆ "Ileana", ┆         ┆ 02:26:18  ┆ "cs.CG"]  │
│           ┆            ┆ Thera…    ┆ Deco…     ┆   ┆ ""], ["…  ┆         ┆ GMT       ┆           │
│ 0704.0003 ┆ Hongjun    ┆ Hongjun   ┆ The       ┆ … ┆ [["Pan",  ┆ v1      ┆ Sun, 1    ┆ ["physics │
│           ┆ Pan        ┆ Pan       ┆ evolution ┆   ┆ "Hongjun" ┆         ┆ Apr 2007  ┆ .gen-ph"] │
│           ┆            ┆           ┆ of the    ┆   ┆ , ""]]    ┆         ┆ 20:46:54  ┆           │
│           ┆            ┆           ┆ Earth-Moo ┆   ┆           ┆         ┆ GMT       ┆           │
│           ┆            ┆           ┆ …         ┆   ┆           ┆         ┆           ┆           │
│ 0704.0004 ┆ David      ┆ David     ┆ A determi ┆ … ┆ [["Callan ┆ v1      ┆ Sat, 31   ┆ ["math.CO │
│           ┆ Callan     ┆ Callan    ┆ nant of   ┆   ┆ ",        ┆         ┆ Mar 2007  ┆ "]        │
│           ┆            ┆           ┆ Stirling  ┆   ┆ "David",  ┆         ┆ 03:16:14  ┆           │
│           ┆            ┆           ┆ cycl…     ┆   ┆ ""]]      ┆         ┆ GMT       ┆           │
│ 0704.0005 ┆ Alberto    ┆ Wael Abu- ┆ From      ┆ … ┆ [["Abu-Sh ┆ v1      ┆ Mon, 2    ┆ ["math.CA │
│           ┆ Torchinsky ┆ Shammala  ┆ dyadic    ┆   ┆ ammala",  ┆         ┆ Apr 2007  ┆ ", "math. │
│           ┆            ┆ and       ┆ $\Lambda_ ┆   ┆ "Wael",   ┆         ┆ 18:09:58  ┆ FA"]      │
│           ┆            ┆ Alberto … ┆ {\alpha}$ ┆   ┆ ""],…     ┆         ┆ GMT       ┆           │
│           ┆            ┆           ┆ …         ┆   ┆           ┆         ┆           ┆           │
└───────────┴────────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

Find duplicates

Most common authors

Heatmap

Time development

Forecast